name: Trigger Meta Repo Update

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  trigger-meta-repo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: property-mappings-server:latest

      - name: Send repository update event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/hubspotdev/CODE-Hub/actions/workflows/update-meta-repo.yml/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "repo": "'"${{ github.repository }}"'",
                "commit": "'"${{ github.sha }}"'",
                "pr_title": "'"${{ github.event.pull_request.title }}"'",
                "pr_url": "'"${{ github.event.pull_request.html_url }}"'"
              }
            }'
